# Generated by Django 6.0.5 on 2026-05-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gameresult_player_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='moves',
            field=models.JSONField(blank=True, default=list, help_text='List of moves played during the game in chronological order'),
        ),
    ]
