# Generated by Django 6.0.6 on 2026-06-13 19:20

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_chesspuzzle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('white_label', models.CharField(default='White', max_length=64)),
                ('black_label', models.CharField(default='Black', max_length=64)),
                ('result', models.CharField(default='*', max_length=7)),
                ('termination', models.CharField(default='unknown', max_length=32)),
                ('pgn', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=game.models._expires_at_default)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
