# Generated by Django 6.0.6 on 2026-06-14 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_gamerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='replay_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gamerecord'),
        ),
    ]
