# Generated by Django 6.0.6 on 2026-06-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_discussion_reply'),
        ('game', '0022_gamerecord_user'),
    ]

    operations = [
    ]
