# Generated by Django 6.0.5 on 2026-06-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_discussionbookmark'),
        ('game', '0023_merge_20260618_2322'),
    ]

    operations = [
    ]
