# Generated by Django 6.0.6 on 2026-06-22 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_merge_0020_discussion_reply_0022_gamerecord_user'),
        ('game', '0023_merge_20260618_2322'),
    ]

    operations = [
    ]
