# Generated by Django 6.0.5 on 2026-06-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_merge_20260619_2154'),
        ('game', '0024_merge_20260622_1925'),
    ]

    operations = [
    ]
